TrajectoryPlannerROS:

  holonomic_robot: false

  # add 
  # controller_frequency: 10.0  to avoid Map update loop warning [20.0]
  meter_scoring: true
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance : 0.10
  sim_time: 1.0
  pdist_scale: 0.6
  max_vel_x: 0.5 # 1.0 # default 0.5
  max_vel_theta: 2.0 # 2.0 # default 1.0
  min_vel_theta: -2.0 # -2.0 # default -1.0
